### ISSUE TITLE
dataset.py problem

### ISSUE THREAD

**Issue by wfs233** [c3sr/split-ner#3]
Why does the code in dataset.py use the get_char_ids method instead of the get_pattern_ids method when acquiring batch["pattern_ids"]?

Line 662

        # pattern_ids
        if self.args.use_char_cnn in ["pattern", "both", "both-flair"]:
            batch_pattern = [[NerDataset.make_pattern(word, self.args.pattern_type)
                              for word in entry[self.args.token_type]] for entry in features]
            pattern_vocab = NerDataset.get_pattern_vocab(self.args.pattern_type)
            batch["pattern_ids"] = NerDataset.get_char_ids(batch_pattern, max_len, pattern_vocab)

**Comment by jatinarora2702** [comment]
Thanks for your question @wfs233. Once a word is converted into a pattern encoding, we treat it in the same way as normal chars. Hence, we are using the same function, `NerDataset.get_char_ids`. But notice that args `batch_pattern` and `pattern_vocab` are passed here to distinguish that we are working with patterns here.

Agreed that having additional function `get_pattern_ids()` is confusing. It is a legacy function and is not used anywhere in the codebase now. Please feel free to contribute and remove it! Otherwise, we'll take it up in the next release. Thanks! :)
